export const tokens = {
  color: {
    background: {
      primary: 'var(--color-bg-primary)',
      secondary: 'var(--color-bg-secondary)',
      tertiary: 'var(--color-bg-tertiary)',
      inverse: 'var(--color-bg-inverse)',
    },
    surface: {
      primary: 'var(--color-surface-primary)',
      muted: 'var(--color-surface-muted)',
      hover: 'var(--color-surface-hover)',
    },
    border: {
      light: 'var(--color-border-light)',
      medium: 'var(--color-border-medium)',
      focus: 'var(--color-border-focus)',
    },
    text: {
      primary: 'var(--color-text-primary)',
      secondary: 'var(--color-text-secondary)',
      muted: 'var(--color-text-muted)',
      inverse: 'var(--color-text-inverse)',
    },
    primary: {
      DEFAULT: 'var(--color-primary)',
      hover: 'var(--color-primary-hover)',
      light: 'var(--color-primary-light)',
      foreground: 'var(--color-primary-foreground)',
    },
    success: {
      DEFAULT: 'var(--color-success)',
      light: 'var(--color-success-light)',
      foreground: 'var(--color-success-foreground)',
    },
    warning: {
      DEFAULT: 'var(--color-warning)',
      light: 'var(--color-warning-light)',
      foreground: 'var(--color-warning-foreground)',
    },
    error: {
      DEFAULT: 'var(--color-error)',
      light: 'var(--color-error-light)',
      foreground: 'var(--color-error-foreground)',
    },
    info: {
      DEFAULT: 'var(--color-info)',
      light: 'var(--color-info-light)',
      foreground: 'var(--color-info-foreground)',
    },
    ai: {
      DEFAULT: 'var(--color-ai)',
      light: 'var(--color-ai-light)',
      foreground: 'var(--color-ai-foreground)',
    },
    sidebar: {
      background: 'var(--color-sidebar-bg)',
      text: 'var(--color-sidebar-text)',
      textMuted: 'var(--color-sidebar-text-muted)',
      activeBg: 'var(--color-sidebar-active-bg)',
      activeText: 'var(--color-sidebar-active-text)',
      border: 'var(--color-sidebar-border)',
      indicator: 'var(--color-sidebar-indicator)',
    },
    channel: {
      whatsapp: 'var(--color-channel-whatsapp)',
      whatsappLight: 'var(--color-channel-whatsapp-light)',
      instagram: 'var(--color-channel-instagram)',
      instagramLight: 'var(--color-channel-instagram-light)',
      facebook: 'var(--color-channel-facebook)',
      facebookLight: 'var(--color-channel-facebook-light)',
      website: 'var(--color-channel-website)',
      websiteLight: 'var(--color-channel-website-light)',
      telegram: 'var(--color-channel-telegram)',
      telegramLight: 'var(--color-channel-telegram-light)',
    },
  },

  radius: {
    none: '0',
    sm: 'var(--radius-sm, 0.25rem)',
    DEFAULT: 'var(--radius, 0.5rem)',
    md: 'var(--radius-md, 0.75rem)',
    lg: 'var(--radius-lg, 1rem)',
    xl: 'var(--radius-xl, 1.5rem)',
    full: '9999px',
  },

  shadow: {
    none: 'none',
    sm: 'var(--shadow-sm, 0 1px 2px 0 rgb(0 0 0 / 0.05))',
    DEFAULT: 'var(--shadow, 0 1px 3px 0 rgb(0 0 0 / 0.1), 0 1px 2px -1px rgb(0 0 0 / 0.1))',
    md: 'var(--shadow-md, 0 4px 6px -1px rgb(0 0 0 / 0.1), 0 2px 4px -2px rgb(0 0 0 / 0.1))',
    lg: 'var(--shadow-lg, 0 10px 15px -3px rgb(0 0 0 / 0.1), 0 4px 6px -4px rgb(0 0 0 / 0.1))',
    xl: 'var(--shadow-xl, 0 20px 25px -5px rgb(0 0 0 / 0.1), 0 8px 10px -6px rgb(0 0 0 / 0.1))',
    inner: 'var(--shadow-inner, inset 0 2px 4px 0 rgb(0 0 0 / 0.05))',
    focus: 'var(--shadow-focus, 0 0 0 3px var(--color-primary-light))',
  },

  spacing: {
    0: '0',
    1: 'var(--spacing-1, 0.25rem)',
    2: 'var(--spacing-2, 0.5rem)',
    3: 'var(--spacing-3, 0.75rem)',
    4: 'var(--spacing-4, 1rem)',
    5: 'var(--spacing-5, 1.25rem)',
    6: 'var(--spacing-6, 1.5rem)',
    8: 'var(--spacing-8, 2rem)',
    10: 'var(--spacing-10, 2.5rem)',
    12: 'var(--spacing-12, 3rem)',
    16: 'var(--spacing-16, 4rem)',
    20: 'var(--spacing-20, 5rem)',
    24: 'var(--spacing-24, 6rem)',
  },

  typography: {
    fontFamily: {
      sans: 'var(--font-sans, "Inter", system-ui, sans-serif)',
      mono: 'var(--font-mono, "JetBrains Mono", monospace)',
    },
    fontSize: {
      xs: ['var(--text-xs, 0.75rem)', { lineHeight: 'var(--leading-xs, 1rem)', letterSpacing: '0.02em' }],
      sm: ['var(--text-sm, 0.875rem)', { lineHeight: 'var(--leading-sm, 1.25rem)', letterSpacing: '0.01em' }],
      base: ['var(--text-base, 1rem)', { lineHeight: 'var(--leading-base, 1.5rem)', letterSpacing: '0' }],
      lg: ['var(--text-lg, 1.125rem)', { lineHeight: 'var(--leading-lg, 1.75rem)', letterSpacing: '-0.01em' }],
      xl: ['var(--text-xl, 1.25rem)', { lineHeight: 'var(--leading-xl, 1.75rem)', letterSpacing: '-0.01em' }],
      '2xl': ['var(--text-2xl, 1.5rem)', { lineHeight: 'var(--leading-2xl, 2rem)', letterSpacing: '-0.02em' }],
      '3xl': ['var(--text-3xl, 1.875rem)', { lineHeight: 'var(--leading-3xl, 2.25rem)', letterSpacing: '-0.02em' }],
      '4xl': ['var(--text-4xl, 2.25rem)', { lineHeight: 'var(--leading-4xl, 2.5rem)', letterSpacing: '-0.03em' }],
    },
    fontWeight: {
      normal: '400',
      medium: '500',
      semibold: '600',
      bold: '700',
    },
    lineHeight: {
      tight: '1.25',
      normal: '1.5',
      relaxed: '1.75',
    },
  },

  transition: {
    fast: 'var(--transition-fast, 150ms ease-out)',
    DEFAULT: 'var(--transition, 200ms ease-out)',
    slow: 'var(--transition-slow, 300ms ease-out)',
  },

  zIndex: {
    hide: -1,
    base: 0,
    dropdown: 1000,
    sticky: 1100,
    modal: 1200,
    popover: 1300,
    tooltip: 1400,
    toast: 1500,
  },

  breakpoint: {
    sm: '640px',
    md: '768px',
    lg: '1024px',
    xl: '1280px',
    '2xl': '1536px',
  },
};

export const semanticColors = {
  light: {
    '--color-bg-primary': '#ffffff',
    '--color-bg-secondary': '#f8fafc',
    '--color-bg-tertiary': '#f1f5f9',
    '--color-bg-inverse': '#0f172a',
    '--color-surface-primary': '#ffffff',
    '--color-surface-muted': '#f1f5f9',
    '--color-surface-hover': '#e2e8f0',
    '--color-border-light': '#e2e8f0',
    '--color-border-medium': '#cbd5e1',
    '--color-border-focus': '#2563eb',
    '--color-text-primary': '#0f172a',
    '--color-text-secondary': '#475569',
    '--color-text-muted': '#94a3b8',
    '--color-text-inverse': '#ffffff',
    '--color-primary': '#2563eb',
    '--color-primary-hover': '#1d4ed8',
    '--color-primary-light': '#dbeafe',
    '--color-primary-foreground': '#ffffff',
    '--color-success': '#059669',
    '--color-success-light': '#d1fae5',
    '--color-success-foreground': '#ffffff',
    '--color-warning': '#d97706',
    '--color-warning-light': '#fef3c7',
    '--color-warning-foreground': '#92400e',
    '--color-error': '#dc2626',
    '--color-error-light': '#fee2e2',
    '--color-error-foreground': '#ffffff',
    '--color-info': '#0284c7',
    '--color-info-light': '#e0f2fe',
    '--color-info-foreground': '#ffffff',
    '--color-ai': '#7c3aed',
    '--color-ai-light': '#ede9fe',
    '--color-ai-foreground': '#ffffff',
    '--color-sidebar-bg': '#0f172a',
    '--color-sidebar-text': '#f1f5f9',
    '--color-sidebar-text-muted': '#94a3b8',
    '--color-sidebar-active-bg': '#1e293b',
    '--color-sidebar-active-text': '#ffffff',
    '--color-sidebar-border': '#1e293b',
    '--color-sidebar-indicator': '#2563eb',
    '--color-channel-whatsapp': '#25d366',
    '--color-channel-whatsapp-light': '#dcfce7',
    '--color-channel-instagram': '#e1306c',
    '--color-channel-instagram-light': '#fce7f3',
    '--color-channel-facebook': '#1877f2',
    '--color-channel-facebook-light': '#dbeafe',
    '--color-channel-website': '#2563eb',
    '--color-channel-website-light': '#dbeafe',
    '--color-channel-telegram': '#2563eb',
    '--color-channel-telegram-light': '#dbeafe',
  },
  dark: {
    '--color-bg-primary': '#0f172a',
    '--color-bg-secondary': '#111827',
    '--color-bg-tertiary': '#1f2937',
    '--color-bg-inverse': '#ffffff',
    '--color-surface-primary': '#1e293b',
    '--color-surface-muted': '#334155',
    '--color-surface-hover': '#334155',
    '--color-border-light': '#334155',
    '--color-border-medium': '#475569',
    '--color-border-focus': '#3b82f6',
    '--color-text-primary': '#f8fafc',
    '--color-text-secondary': '#cbd5e1',
    '--color-text-muted': '#64748b',
    '--color-text-inverse': '#0f172a',
    '--color-primary': '#3b82f6',
    '--color-primary-hover': '#60a5fa',
    '--color-primary-light': '#1e3a5f',
    '--color-primary-foreground': '#ffffff',
    '--color-success': '#10b981',
    '--color-success-light': '#064e3b',
    '--color-success-foreground': '#ffffff',
    '--color-warning': '#f59e0b',
    '--color-warning-light': '#78350f',
    '--color-warning-foreground': '#ffffff',
    '--color-error': '#ef4444',
    '--color-error-light': '#7f1d1d',
    '--color-error-foreground': '#ffffff',
    '--color-info': '#06b6d4',
    '--color-info-light': '#164e63',
    '--color-info-foreground': '#ffffff',
    '--color-ai': '#a78bfa',
    '--color-ai-light': '#3c2a5e',
    '--color-ai-foreground': '#ffffff',
    '--color-sidebar-bg': '#08101a',
    '--color-sidebar-text': '#f1f5f9',
    '--color-sidebar-text-muted': '#94a3b8',
    '--color-sidebar-active-bg': '#1e293b',
    '--color-sidebar-active-text': '#ffffff',
    '--color-sidebar-border': '#1e293b',
    '--color-sidebar-indicator': '#3b82f6',
    '--color-channel-whatsapp': '#25d366',
    '--color-channel-whatsapp-light': '#064e3b',
    '--color-channel-instagram': '#e1306c',
    '--color-channel-instagram-light': '#500724',
    '--color-channel-facebook': '#1877f2',
    '--color-channel-facebook-light': '#1e3a5f',
    '--color-channel-website': '#3b82f6',
    '--color-channel-website-light': '#1e3a5f',
    '--color-channel-telegram': '#3b82f6',
    '--color-channel-telegram-light': '#1e3a5f',
  },
};

export default tokens;